[build]
command = "cd client/web && npm install && npm run build && cd ../../functions/subscribe && npm install"
functions = "functions"

[dev]
command = "cd client/web && npm start"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"