[build]
command = "cd client/web && npm install && npm run build && cd ../../functions/subscribe && npm install"
functions = "functions"

[dev]
command = "cd client/web && npm start"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200